<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit0f3cc8adef51b1f9c8b0ce1d09c5a178
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PhpOffice\\PhpProject\\' => 21,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PhpOffice\\PhpProject\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpoffice/phpproject/src/PhpProject',
        ),
    );

    public static $prefixesPsr0 = array (
        'P' => 
        array (
            'PHPProject' => 
            array (
                0 => __DIR__ . '/..' . '/phpoffice/phpproject/src',
            ),
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit0f3cc8adef51b1f9c8b0ce1d09c5a178::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit0f3cc8adef51b1f9c8b0ce1d09c5a178::$prefixDirsPsr4;
            $loader->prefixesPsr0 = ComposerStaticInit0f3cc8adef51b1f9c8b0ce1d09c5a178::$prefixesPsr0;

        }, null, ClassLoader::class);
    }
}
